# Generated by Django 2.1.4 on 2020-01-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMaskDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(null=True)),
                ('avg_x', models.FloatField(null=True)),
                ('avg_y', models.FloatField(null=True)),
                ('mass', models.IntegerField(null=True)),
                ('major_minor', models.FloatField(null=True)),
                ('com_x', models.FloatField(null=True)),
                ('com_y', models.FloatField(null=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='IsroBackend.ImageFileName')),
            ],
        ),
    ]
