# Generated by Django 2.1.4 on 2020-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('top_temp', models.FloatField(null=True)),
                ('top_height', models.FloatField(null=True)),
                ('cloud_type', models.TextField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
