# Generated by Django 2.1.4 on 2020-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0002_imagepreds'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreds',
            name='pix_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imagepreds',
            name='pix_y',
            field=models.FloatField(null=True),
        ),
    ]
