# Generated by Django 2.1.4 on 2020-01-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IsroBackend', '0003_auto_20200117_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepreds',
            name='pix_x',
        ),
    ]
